# Generated by Django 5.0.1 on 2024-01-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylink',
            old_name='shorted_link',
            new_name='slug',
        ),
    ]
