# Generated by Django 5.1.7 on 2025-03-27 11:17

import django.db.models.deletion
import django.utils.timezone
import linkshortener.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0004_mylink_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylink',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mylink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mylink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mylink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mylink',
            name='hash',
            field=models.CharField(default=linkshortener.utils.generate_unique_hash, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='LinkAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='linkshortener.mylink')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
